### ISSUE TITLE
Unable to extract date

### ISSUE THREAD

**Issue by anas-incedo** [vbhavsingh/DateParser#5]
Here is the string "Scheduled to be cancelled by 2018-09-24T21:14:13.877Z" (without quotes).
I get 0 dates in the result.

**Comment by vbhavsingh** [comment]
The date format, containing "T" as Date and Time separator is yet not supported. If you remove 'T', it will work.
However, thanks for bringing this use case to my notice, I will add support in next release, which I will be making by next week.

**Comment by vbhavsingh** [comment]
I have completed the release earlier. You can use this code, it will work for your case.
